<?php
// api/submit_enrollment.php
// Final submission endpoint: stores to DB (if configured) and sends an HTML email.
// In dev (DDEV), PHP mail() is captured by Mailpit. In production, mail() sends via WHC.

header('Content-Type: application/json');

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(405);
    echo json_encode(['success' => false, 'error' => 'Method not allowed']);
    exit;
}

$raw = file_get_contents('php://input');
$data = json_decode($raw, true);

// Safer payload validation: ensure "data" exists and is an array
if (
    !is_array($data) ||
    empty($data['formId']) ||
    !isset($data['data']) ||
    !is_array($data['data'])
) {
    http_response_code(400);
    echo json_encode(['success' => false, 'error' => 'Invalid payload']);
    exit;
}

$formId    = (string) $data['formId'];
$sessionId = isset($data['sessionId']) ? (string) $data['sessionId'] : '';
$submittedIso = isset($data['submittedAt']) ? (string) $data['submittedAt'] : date('c');
$fields    = $data['data'];

// Normalize submittedAt to a MySQL DATETIME
$submittedAt = date('Y-m-d H:i:s', strtotime($submittedIso));
if ($submittedAt === false) {
    $submittedAt = date('Y-m-d H:i:s');
}

// Optional: full HTML preview table generated by the front-end
$emailHtmlFromClient = '';
if (!empty($data['emailHtml']) && is_string($data['emailHtml'])) {
    $emailHtmlFromClient = $data['emailHtml'];
}

$config = require __DIR__ . '/config.php';

// 1) Save to DB (optional)
$dbSaved = false;

if (!empty($config['db']['dsn'])) {
    try {
        $pdo = new PDO(
            $config['db']['dsn'],
            $config['db']['user'],
            $config['db']['password'],
            [
                PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            ]
        );

        $jsonData = json_encode($fields, JSON_UNESCAPED_UNICODE);

        // Simpler, always-do-it upsert based on (form_id, session_id)
        // Requires UNIQUE KEY on (form_id, session_id) as in enrollment_schema.sql
        $sql = "INSERT INTO enrollments (form_id, session_id, submitted_at, data_json, status)
                VALUES (:f, :s, :t, :j, 'submitted')
                ON DUPLICATE KEY UPDATE
                    data_json    = VALUES(data_json),
                    status       = 'submitted',
                    submitted_at = VALUES(submitted_at),
                    updated_at   = NOW()";

        $stmt = $pdo->prepare($sql);
        $stmt->execute([
            ':f' => $formId,
            ':s' => $sessionId,
            ':t' => $submittedAt,
            ':j' => $jsonData,
        ]);

        $dbSaved = true;
    } catch (Throwable $e) {
        // DB is optional; failures should not block email send
        $dbSaved = false;

        // Optional: log DB error while we are debugging on staging
        /*
        $logFile = __DIR__ . '/../submit_enrollment.log';
        @file_put_contents(
            $logFile,
            date('c') . ' DB ERROR: ' . $e->getMessage() . PHP_EOL,
            FILE_APPEND
        );
        */
    }
}

// 2) Build email HTML
function escape_html($s)
{
    return htmlspecialchars((string) $s, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}

// If the front-end sent a fully-rendered preview table (with friendly labels),
// prefer that. Otherwise, fall back to a simple key/value table using raw names.
if (!empty($emailHtmlFromClient)) {
    $emailHtml = $emailHtmlFromClient;
} else {
    $rows = '';
    foreach ($fields as $k => $v) {
        if (is_array($v)) {
            $v = implode(', ', $v);
        }
        $rows .= '<tr><td style="border:1px solid #e5e7eb;padding:6px 8px;font-weight:600;width:38%;">'
              . escape_html($k)
              . '</td><td style="border:1px solid #e5e7eb;padding:6px 8px;">'
              . escape_html($v)
              . '</td></tr>';
    }

    $emailHtml = '<div style="font-family:system-ui,-apple-system,Segoe UI,Roboto,Arial,sans-serif;">
      <h2 style="margin:0 0 10px;">GRASP Enrollment Submission</h2>
      <p style="margin:0 0 12px;">Submitted at: ' . escape_html($submittedIso) . '</p>
      <table style="border-collapse:collapse;width:100%;max-width:900px;">' . $rows . '</table>
    </div>';
}

// Subject and headers
$subject = isset($config['email_subject'])
     ? $config['email_subject']
     : 'New GRASP Enrollment Submission';

// $subject = 'GRASP TEST ' . date('H:i:s');


$to   = isset($config['email_to']) ? $config['email_to'] : '';
$from = isset($config['email_from']) ? $config['email_from'] : 'no-reply@example.com';

if (empty($to)) {
    echo json_encode([
        'success' => false,
        'error'   => 'Email recipient not configured',
        'dbSaved' => $dbSaved,
    ]);
    exit;
}

// Use parent email for Reply-To if available
$parentEmail = '';
foreach (['parent1_email', 'parent_email', 'guardian_email', 'email'] as $key) {
    if (!empty($fields[$key]) && filter_var($fields[$key], FILTER_VALIDATE_EMAIL)) {
        $parentEmail = $fields[$key];
        break;
    }
}
/*

// from mail_test.php
    'From: ' . $from,
    'Reply-To: ' . $from,
    'X-Mailer: PHP/' . phpversion(),
    'MIME-Version: 1.0',
    'Content-type: text/plain; charset=UTF-8',

*/
$headers = [];
$headers[] = 'From: ' . $from;

//if (!empty($parentEmail)) {
//    $headers[] = 'Reply-To: ' . $parentEmail;
//}
// TEMP: match mail_test headers – do NOT use parent email here
$headers[] = 'Reply-To: ' . $from;

$headers[] = 'X-Mailer: PHP/' . phpversion();
$headers[] = 'MIME-Version: 1.0';
// $headers[] = 'Content-type: text/html; charset=UTF-8';
$headers[] = 'Content-type: text/html; charset=UTF-8';
if (!empty($config['email_bcc'])) {
    $headers[] = 'Bcc: ' . $config['email_bcc'];
}




// Send email
// RFC 5321: max line length is 998 characters. Wrap body to a safe width so
// no single line is too long for the receiving mail server.
$emailBodyForMail = wordwrap($emailHtml, 900, "\r\n", true);

$success = @mail($to, $subject, $emailBodyForMail, implode("\r\n", $headers));

// Optional: log outcome while debugging on staging

$logFile = __DIR__ . '/../submit_enrollment.log';
@file_put_contents(
    $logFile,
    date('c')
    . ' host=' . ($_SERVER['HTTP_HOST'] ?? '')
    . ' uri='  . ($_SERVER['REQUEST_URI'] ?? '')
    . ' success=' . var_export($success, true)
    . ' dbSaved=' . var_export($dbSaved, true)
    . ' to=' . $to
    . PHP_EOL,
    FILE_APPEND
);


echo json_encode([
    'success' => (bool) $success,
    'dbSaved' => $dbSaved,
]);
